histogram_path: ./Output histograms
input_image_path: ./Cancerous cell smears
output_image_path: ./Output images
output_statistics_path: ./Output statistics
processing_steps:
- {channel: null, file_prefix: cyl01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: cyl01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: cyl01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: inter01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: inter01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: inter01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: let01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: let01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: let01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: mod01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: mod01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: mod01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: para01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: para01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: para01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: super01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: super01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: super01_k_means_with_loc, function: save_image_set}
- {channel: null, file_prefix: svar01, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, function: k_means_clustering, k: 3, return_batch_name: batch12,
  use_loc: true}
- {arg_batch_name: batch1, file_prefix: svar01_greyscale, function: save_image_set}
- {arg_batch_name: batch12, file_prefix: svar01_k_means_with_loc, function: save_image_set}
