histogram_path: ./Output histograms
input_image_path: ./Cancerous cell smears
output_datasets_path: ./Output datasets
output_image_path: ./Output images
output_statistics_path: ./Output statistics
processing_steps:
- {channel: null, file_prefix: cyl, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: cyl, function: extract_features}
- {channel: null, file_prefix: inter, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: inter, function: extract_features}
- {channel: null, file_prefix: let, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: let, function: extract_features}
- {channel: null, file_prefix: mod, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: mod, function: extract_features}
- {channel: null, file_prefix: para, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: para, function: extract_features}
- {channel: null, file_prefix: super, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: super, function: extract_features}
- {channel: null, file_prefix: svar, function: load_image_set, return_batch_name: batch1}
- {arg_batch_name: batch1, dataset_name: dataset, file_prefix: svar, function: extract_features}
- {dataset_name: dataset, file_name: dataset, function: save_dataset}
- {dataset_name: dataset, file_name: dataset, function: load_dataset}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 1}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 3}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 5}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 7}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 13}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 21}
- {dataset_name: dataset, function: k_nearest_neighbors, k: 99}
